server:
    port: 8081

file:
    storage:
        location: fileStorage

spring:
    servlet:
        multipart:
            enabled: true
            location: temp123
            file-size-threshold: 5MB
            max-file-size: 6MB
            max-request-size: 15MB
            
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/uz?allowPublicKeyRetrieval=true&useSSL=true
        user: root
        password: farai@1995
        driver-class-name: com.mysql.cj.jdbc.Driver


            